export type EventStatus = 'Triggered' | 'Acknowledged' | 'Resolved' | 'Deferred';
export type EventSource = 'Monitoring' | 'Paging';
export type EventUrgency = 'High' | 'Medium' | 'Low';

export interface EventItem {
  id: string;
  alertName: string;
  source: EventSource;
  urgency: EventUrgency;
  createdAt: string;
  status: EventStatus;
  actedOnBy: string;
  activeTime: string;
  responders: string;
  teams: string;
  services: string;
  isChild?: boolean;
  parentId?: string;
}

export const ROOTLY_EVENTS_DATASET: EventItem[] = [
  {
    id: 'H4cavG',
    alertName: '[Demo] Elevated 5xx (edge)',
    source: 'Monitoring',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Triggered',
    actedOnBy: '—',
    activeTime: '18h',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: 'yHIkYQ',
    alertName: '[Demo] Checkout 5xx rate > 2%',
    source: 'Monitoring',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '00:33:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: 'Xo0VUt',
    alertName: '[Demo] Checkout error budget burn',
    source: 'Paging',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Acknowledged',
    actedOnBy: '—',
    activeTime: '21h',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
    isChild: true,
    parentId: 'yHIkYQ',
  },
  {
    id: '4HS5eE',
    alertName: '[Demo] Checkout p99 latency > 1s',
    source: 'Monitoring',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '02:12:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
    isChild: true,
    parentId: 'yHIkYQ',
  },
  {
    id: 'uuM1s4',
    alertName: '[Demo] Disk usage > 85% (db-1)',
    source: 'Monitoring',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Acknowledged',
    actedOnBy: '—',
    activeTime: '1d 10h',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: 'SV7kXt',
    alertName: '[Demo] Auth login p99 > 2s',
    source: 'Paging',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '00:09:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: 'Wj2T5Y',
    alertName: '[Demo] Auth connection pool saturated',
    source: 'Monitoring',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '00:21:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: 'mMgdxe',
    alertName: '[Demo] Connection-pooler pool saturation 100%',
    source: 'Monitoring',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '01:08:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: 'kNY3G4',
    alertName: '[Demo] Payments confirmation success rate < 90%',
    source: 'Paging',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '00:21:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: 'irnvua',
    alertName: '[Demo] Checkout 5xx rate > 30%',
    source: 'Monitoring',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '03:04:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: 'TCus8n',
    alertName: '[Demo] Primary database health check failing',
    source: 'Monitoring',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '00:47:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: 'Vb1FQn',
    alertName: '[Demo] Payment status update latency > 5m',
    source: 'Paging',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '03:04:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: '3XLZsp',
    alertName: '[Demo] Payments webhook queue depth > 10k',
    source: 'Monitoring',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '00:47:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: 'V9pQow',
    alertName: '[Demo] Search empty-result rate elevated',
    source: 'Monitoring',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Deferred',
    actedOnBy: '—',
    activeTime: '1w',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: '5ScEjg',
    alertName: '[Demo] Search index cache hit rate low',
    source: 'Monitoring',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '00:14:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
  {
    id: 'Lf5L2l',
    alertName: '[Demo] Nightly job missed SLA',
    source: 'Paging',
    urgency: 'High',
    createdAt: 'Sep 5, 2026',
    status: 'Resolved',
    actedOnBy: '—',
    activeTime: '00:09:00',
    responders: '—',
    teams: '—',
    services: '[Demo] DB - Production Database',
  },
];
